[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }

#    kotlin("jvm") version "2.1.0"
#    id("fabric-loom") version "1.9-SNAPSHOT"
#    id("maven-publish")

[versions]

# This Mod Version
mod_version = "0.1"
loom = "1.11-SNAPSHOT"
kotlin = "2.2.0"
fabric_language_kotlin = "1.13.0+kotlin.2.1.0"
kotlin_serialization_minecraft = "2.0.0+1.20.1"


#minecraft_version=1.21.4
#yarn_mappings=1.21.4+build.8
#loader_version=0.16.10
#kotlin_loader_version=1.13.0+kotlin.2.1.0
## Mod Properties
#mod_version=0.1
#maven_group=io.github.natanfudge
#archives_base_name=hardcraft
## Dependencies
## check this on https://modmuss50.me/fabric.html
#fabric_version=0.115.0+1.21.4
# Minecraft
minecraft = "1.20.1"
wthit_fabric="fabric-8.16.1"

# Mods & Libraries
yarn_mappings = "1.20.1+build.10"
fabric_loader = "0.16.10"
fabric_api = "0.92.6+1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }
kotlin_test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin_serialization_minecraft = { module = "io.github.natanfudge:kotlinx-serialization-minecraft", version.ref = "kotlin_serialization_minecraft" }
wthit-api={module = "mcp.mobius.waila:wthit-api", version.ref = "wthit_fabric"}
wthit-fabric={module = "mcp.mobius.waila:wthit", version.ref = "wthit_fabric"}